### ISSUE TITLE
Incompatible with HDCP Protected Content (Netflix)

### ISSUE THREAD

**Issue by Terrobility** [ledoge/dwm_lut#12]
When playing DRM protected content, HDCP activates and causes one or two black flashes of the screen. The LUT is unloaded. The application status becomes "Inactive". And the video begins playing.

As a reminder, High-bandwidth Digital Content Protection (HDCP) is used for DRM on video streaming services.

Instructions:
1. Launch `dwm_lut` and press Apply
2. Log into a video streaming platform, like Netflix, Amazon Prime, BBC iPlayer, etc.
3. Play a video
(I recommend testing on Firefox. It shows a HDCP icon in the address bar whenever it kicks in.)

I don't know what you could do about this. Maybe reactivate once HDCP is no longer active?

**Comment by ledoge** [comment]
>causes one or two black flashes of the screen. The LUT is unloaded. The application status becomes "Inactive".

This means that DWM crashes and then gets restarted. I'll have to see if I can debug this properly (can't use a VM, since HDCP won't work there) and figure out if there's something I can do to prevent that crash.

**Comment by ledoge** [comment]
Should be fixed in the new release, test it and let me know if it works on your machine.

**Comment by Terrobility** [comment]
I tested it and it seems to be perfect.

But I have a suggestion: In the application status, maybe it could show "Active (HDCP unloaded)" instead of just "Active"?

Also, out of curiosity. Would it be possible in these situations to just load 1DLUT (VCGT)? This works nearly everywhere and would be better than having no correction at all. You could just copy how DisplayCAL loads its profiles into VCGT.

**Comment by ledoge** [comment]
Thanks!

>maybe it could show "Active (HDCP unloaded)" instead of just "Active"?

Not really possible with how it's currently implemented, as the GUI isn't aware of whether the DLL is applying the LUT to a monitor right now or not. Also, if you have one monitor where it's working normally and one where it's disabled due to HDCP, it's not clear what it should show in that case.

>Would it be possible in these situations to just load 1DLUT (VCGT)

It would indeed be better than having nothing at all, but that's out of scope for this project, sorry.

**Comment by Terrobility** [comment]
> Also, if you have one monitor where it's working normally and one where it's disabled due to HDCP, it's not clear what it should show in that case.

It's not like that. When HDCP kicks in, the LUT unloads on all monitors. It seems to be a global thing, not per-monitor.
