### ISSUE TITLE
Adaptive Sync Not Working

### ISSUE THREAD

**Issue by perrinpagess** [ledoge/dwm_lut#13]
Hi,

Thanks for making this program! When I apply a 3dlut, Adaptive Sync is disabled. I do not game, but the windows Movies & TV UWP video player uses Adaptive Sync to match the display + video framerates to eliminate judder. Is this something that can be fixed?

**Comment by ledoge** [comment]
I don't think so, unfortunately, as adaptive sync seems to rely on features that need to be disabled for the LUT to work. I've uploaded a slightly modified build [here](https://github.com/ledoge/dwm_lut/files/7613524/dwm_lut.zip) where these features are not disabled, but my guess is that this will just result in adaptive sync working but the LUT not actually being applied to the video player.

**Comment by perrinpagess** [comment]
In the modified build adaptive sync works, but the video frame is black unless in full screen and the lut doesn't get applied :( A small problem nonetheless. 

Microsoft seems to deploy their own lut on surface devices for factory calibration (I have an intel surface laptop 3) through an hid driver called 'surface color profile' that you can enable or disable in device manager. It is poor quality and introduces banding...do you think this is just intel's proprietary lut driver rebranded? Surface drivers are free to download from microsoft if that's worth investigating.

Anyway, thanks for the response!

**Comment by CrendKing** [comment]
Was about to report this myself. Thanks for the modified version. May I suggest that adding the modified version as an option in the main program? Some people may value being able to play games tear-free and responsive higher than color accurate in fast-paced games, if both can't be achieved simultaneously.

**Comment by ledoge** [comment]
>but the video frame is black unless in full screen

Oh right, the way it works it the actual desktop backbuffer is supposed to have an alpha value of 0 in those regions so that e.g. the video player can get "overlayed" there, but I always redraw with an alpha value of 1, so it ends up being blacked out.

The problem with leaving those features enabled is that it breaks pretty much everything. E.g. when you have a Chrome window open, it'll randomly switch between being MPO'd and being rendered normally, which means its colors would flash between the unmodified and the corrected ones multiple times per second. And allowing DirectFlip to work means that e.g. fullscreen video playback in Chrome also bypasses the LUT.

**Comment by CrendKing** [comment]
Alternatively, people could write a script to turn off DwmLut when launching a game, and turn it back on when the game is finished. There is some "game mode" feature in Windows. Is there API for apps to hook? Can DwmLut turn itself off when detecting a game?

**Comment by ledoge** [comment]
>Microsoft seems to deploy their own lut on surface devices for factory calibration 

Very interesting stuff, I tried to look into but didn't really get anywhere... Unfortunately I don't have a Surface device myself.

>There is some "game mode" feature in Windows.

Doesn't seem like there's a way to detect if that's active, sadly. And "detecting a game" is very vague and probably impossible to do in a way that works as users would expect.

**Comment by lextra2** [comment]
Uhm, freesync works perfectly fine for me, AMD Radeon RX 5700 + Samsung 55" Q70A. When I bring up the OSD of this tv it shows the fps, which changes (so its working).
