### ISSUE TITLE
Windows Vista compatibility

### ISSUE THREAD

**Issue by Freestalkerdotfr** [ledoge/dwm_lut#15]
Hello there !

I would like to know if your software works with Windows Vista.

**Comment by ledoge** [comment]
DWM changed too much over the years, so only recent versions of Windows 10 (and 11) supported.

**Comment by Freestalkerdotfr** [comment]
THX for the fast reply !

It's too bad as I have a Windows Vista PC at home and wanted to correst the colors.

You can close this issue. ;-)

Thank you once again
