### ISSUE TITLE
Not working with Intel HD3000 

### ISSUE THREAD

**Issue by markanini** [ledoge/dwm_lut#23]
On Windows 11. Says active but no change in color output is seen. Oddly with a generic Microsoft driver active did work as expected. According to GPU-Z the generic driver supports OpenGL 2.1, the Intel driver supports OpenGL 3.1 with many report on the web talking about wonky OpenGL support.

Any testing I can do? Let me know.

**Comment by ledoge** [comment]
Unfortunately your GPU doesn't support DirectX 11, and dwm_lut only works with DWM's DirectX 11 backend.

**Comment by markanini** [comment]
Fair enough. If nothing else the requirements are nerfed in the normal driver and don't have a work around.

**Comment by markanini** [comment]
![image](https://user-images.githubusercontent.com/15148553/163253828-52eb1813-ff2f-467a-bd4a-aa64b99464e0.png)
BTW how is that dwm_lut appears to work with the Microsoft Basic Display Adapter? I assume some software fallback is triggered?(DX11 is not avalaible in GPU-Z) It's the same with iHD3000 and Radeon RX480 I tested.

**Comment by ledoge** [comment]
Not sure. Don't really know anything about how GPU drivers work, but since dwm_lut uses DirectX 11 functions, that basic display adapter driver must support it somehow.
