### ISSUE TITLE
Stopped working on latest Windows 11 22H1 22000.706 update

### ISSUE THREAD

**Issue by aaronmmarks** [ledoge/dwm_lut#26]
It appears dwm_lut is no longer working on Windows 11 22H1 build 22000.706. I'm wondering if Microsoft rolled some of the changes that break 22H2 back into 22H1 22000.706.

**Comment by monchou22** [comment]
Same here.

**Comment by markanini** [comment]
Also experiencing this.

**Comment by markanini** [comment]
BTW Anyone managed to revert this Windows update?

**Comment by V1cti0N** [comment]
Has there been any update? I unfortunately have a version past 22000.675 so I'm hoping it gets fixed :)

**Comment by adbowers** [comment]
I am seeing this as well. I tried recompiling the DLL to see if that would resolve the issue, but was unable to get the build working.

**Comment by ledoge** [comment]
Thanks, just pushed a new release that supports ≥ 708 (and hopefully also 706).
