### ISSUE TITLE
Error - Access to path 0_0.cube is denied.

### ISSUE THREAD

**Issue by TheOld** [ledoge/dwm_lut#29]
Hi ledoge, 

I'm getting the following error when I hit the `Apply` button, after selecting a LUT to apply.
Any ideas on what might be causing it?

For context, the very first time I ran the tool it worked fine, then after trying to load a different LUT file it started throwing this error and I wasn't able to get it working again.

![image](https://user-images.githubusercontent.com/4731404/186046826-1230e7a3-6d3c-4a09-9748-55c27d94d594.png)

---

My OS details:

Edition	Windows 11 Home
Version	21H2
Installed on	‎23/‎08/‎2022
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0

**Comment by TheOld** [comment]
Update: Looks like the app creates one `0_0.cube` file in the `"%SYSTEMROOT%\\Temp\\luts"` folder. 
I suspect one LUT file I was using might be corrupted or malformed (although I was able o apply and observe its effects just like other files).

Deleting the `0_0.cube` file allowed me to apply a LUT again and get the tool back into a working state.

Feel free to close this issue if you think this is no longer relevant.

Thanks.

**Comment by ledoge** [comment]
Very interesting. I'm not sure what exactly can go wrong for that to happen, as it never happened to me in testing. Thanks for the report though, and please let me know if you ever find a way to (at least somewhat) consistently reproduce it.
