### ISSUE TITLE
Dumb Question: How to capture footage with LUTs.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [ledoge/dwm_lut#35]
Trying to make a video tutorial on this but found the weirdest quirk.

Using OBS still shows you the original color when capturing.

**Comment by ectv96** [comment]
give the LUTS on editing software like adobe premiere.

**Comment by EmotiveColor** [comment]
You can load a Lut filter into OBS :) Though you might not want to embed a display correction into a recorded video - that would lead to double correction when played back, or the wrong correction when played on other displays

**Comment by WriteCodeEveryday** [comment]
@EmotiveColor you know, it's funny that you would be the one answering this...

https://www.youtube.com/watch?v=S9YdqzOyZ7M (This was for a GHAlex video)

**Comment by EmotiveColor** [comment]
Ha, it's a small (internet color) world! 
Dwm_lut is an amazing tool by the way (when paired with DisplayCal and i1Display) for accurate color across Windows on every monitor you own. It's just not working anymore with W11 sadly.
