### ISSUE TITLE
Do not use this for games!

### ISSUE THREAD

**Issue by KingCrazyC** [ledoge/dwm_lut#49]

**Comment by Zelminar** [comment]
What they said ^

**Comment by lextra2** [comment]
It doesn't destroy your GPU
And performance penalties are [mentioned here](https://github.com/ledoge/dwm_lut#usage)

**Comment by KingCrazyC** [comment]
Shut your mouth... this shit has a trojan horse with a crypto miner! no wonder it is performance problems with this trash!
