### ISSUE TITLE
blank

### ISSUE THREAD

**Issue by KingCrazyC** [ledoge/dwm_lut#51]
i suddenly saw that my temperature on my cpu was over 10 degrees hotter then it normal at idle then i ran malware bytes and it discovered a trojan horse with a crypto miner... DO NOT DOWNLOAD THIS!

**Comment by Buliwyf-Stonehand** [comment]
Trolling?

**Comment by KingCrazyC** [comment]
No.. but It’s a c# app with open source code. you can compile it and inspect it

**Comment by KingCrazyC** [comment]
It has a trojan horse but i heard that it was normal for open source stuff like this.. so i closed the issue

**Comment by Buliwyf-Stonehand** [comment]
> No.. but It’s a c# app with open source code. you can compile it and inspect it

And where in the source code is this "trojan"?

**Comment by KingCrazyC** [comment]
went to virustotal and it confirmed that the zip file (the one that you download from the Direct Downloads link in the description) is in fact a trojan..

**Comment by KingCrazyC** [comment]
But like i said people told me it was normal but still...

**Comment by Buliwyf-Stonehand** [comment]
> went to virustotal and it confirmed that the zip file (the one that you download from the Direct Downloads link in the description) is in fact a trojan..

Do you know what heuristic analysis is and have you ever heard of "false positives"? Just compile it yourself, upload it to Virustotal and you'll get the same results.

**Comment by KingCrazyC** [comment]
So i can close this issue? btw i use this for games and as you may know you lose some performance when you use it.. but when i create the 3D LUT on displaycal it seems that the more patches i use the worse the performance gets when i apply the 3D LUT.. is it any reason for that?

**Comment by Buliwyf-Stonehand** [comment]
>So i can close this issue?

Yes.
