### ISSUE TITLE
Using LUT with Netflix app causes screen to pixelate

### ISSUE THREAD

**Issue by adbowers** [ledoge/dwm_lut#6]
Applying the LUT while the Netflix app is running causes the screen to become pixelated and unusable. Disabling the LUT immediately resolves the issue. I also tried with the native Hulu and Amazon Prime Video apps and it *did not* reproduce. Not a big deal to turn it off, though.

Example of the issue
https://photos.app.goo.gl/r4ta6sHf8H8NBUUZ8

**Comment by ledoge** [comment]
Do you still get this behavior with the latest release?

**Comment by adbowers** [comment]
I no longer see this issue with the latest (3.3) release. The LUT is not applied with the Netflix UWP app open and is applied once I close it.
