### ISSUE TITLE
Plan to integrate into DisplayCAL and replace their current profile loader?

### ISSUE THREAD

**Issue by CrendKing** [ledoge/dwm_lut#9]
Firstly, thank you for the work on this! I stumbled upon this randomly when I was searching for applying 3D LUT in Windows.

I know you have a [long thread](https://hub.displaycal.net/forums/topic/i-made-a-tool-for-applying-3d-luts-to-the-windows-desktop/) in DisplayCAL forum. I wonder if it's a good idea to use dwm_lut to replace/enhance DisplayCAL's profile loader? The motivation for this integration is mainly so that when user does a calibration, DisplayCAL will know to disable the LUT temporarily.

If integration is not possible, is it possible for dwm_lut to detect the start of DisplayCAL's calibration session and disable itself, provided DwmLutGUI is running in background?

**Comment by ledoge** [comment]
Thank you!

I don't think something like this is easily doable with how it currently works.

1. As of now, I believe the only real way for another program to see if there are active LUTs is to check if `dwm_lut.dll` is loaded in the `dwm.exe` process, but this would require DisplayCAL to run with admin rights.

2. I don't think there's a way for me to detect when DisplayCAL is calibrating vs. for example, running a profile verification (which you'd want to use for measuring the performance of the injected 3D LUT).

Maybe the best option would be to have a background process that can be used to query the state of the LUT and enable/disable it? DisplayCAL could then use that to control the state. Not sure though.

**Comment by CrendKing** [comment]
There are plenty of ways to do [IPC](https://docs.microsoft.com/en-us/windows/win32/ipc/interprocess-communications) in Windows. For example, `WM_COPYDATA` is as easy as creating a window in the "server" side (e.g. dwm_lut), and asking client (e.g. DisplayCAL) to send that message to that window with custom data (e.g. "I'm going to calibrate/verify profile. Do whatever you want with this info"). It's good because it's loose integration (i.e. if no dwm_lut is installed in the computer, that message just send to blackhole without any harm). Of course, this does require some kind of talk of an agreed API between you guys. But even if one side of you doesn't want do commit to an API, the other side can still do it, so that other apps might make use of it. DisplayCAL won't be the only calibration software existed, and dwm_lut won't be the only software to mess with color management, right?
